redis:
  addrs:
    - "localhost:6379"
  password: ""
  db: 0
  poolSize: 1000
eventsRedis:
  addrs:
    - "localhost:6379"
  password: ""
  db: 0
  poolSize: 1000
eventsApiRedis:
  addrs:
    - "localhost:6379"
  password: ""
  db: 1
  poolSize: 1000