postgres:
  maxOpenConns: 10
  maxIdleConns: 1
  connMaxLifetime: 30m
  connection:
    host: postgres
    port: 5432
    user: postgres
    password: psw
    dbname: postgres
    sslmode: disable

metrics:
  port: 9003

pulsar:
  URL: "pulsar://pulsar:6650"
  jobsetEventsTopic: "events"
  receiveTimeout: 5s
  backoffTime: 1s

subscriptionName: "scheduler-ingester"
batchSize: 10000
batchDuration: 500ms
priorityClasses:
  armada-default:
    priority: 1000
  armada-preemptible:
    priority: 1000


